mock/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('myapp/',include("myapp.urls")),
]

myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp"

urlpatterns = [
    path('profile/',views.profile,name="profile"),
    path('contactus/',views.contactus,name="contactus"),
    path('signin/',views.signin,name="signin"),
    path('signup/',views.signup,name="signup"),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def home(request):
    return render(request,"home.html")

def profile(request):
    name="Kishan"
    return render(request,"myapp/profile.html",{'name':name})

def contactus(request):
    return render(request,"myapp/contactus.html")

def signin(request):
    return render(request,"myapp/signin.html")

def signup(request):
    return render(request,"myapp/signup.html")

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Home</title>
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Cookie|Pacifico" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet"href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
    {% include "partials/_navbar.html" %}

    {% block content %}
       <div class="container">
         <div class="jumbotron">
             <h1>Welcome to Home page</h1>
         </div>
       </div>
     {% endblock %}

     {% include "partials/_footer.html" %}
</body>
</html>

templates/myapp/contactus.html
<html>
<title>Contact Us</title>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Cookie|Pacifico" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet"href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .container{
            position:relative;
            text-align:center;
            color:black;
        }
        img{
            height:130%;
            width:100%;
        }
        
        h4{
            font-family:;
            text-align: center;
            font-size: 25px;
        }
        h1{
            
            font-size: 40px;
            text-align: center;
        }
        p{
           
            font-size:25px;
        }
        .top-left{
            position:absolute;
            top:8px;
            left:16px;
            
        }
        .fa{
            padding:20px;
            font-size:30px;
            width:80px;
            text-align:center;
            text-decoration: none;
            margin:5px 2px;
        }
        
         .fa:hover{
            opacity:0.7;
            
        }

        </style>
    </head>
    <body>
        {% include "partials/_navbar.html" %}
        <div class="container">
        
        <h1>Contact Us!</h1>
        <p>Mob:1234567890</p>
        <form>
            <div class="form-group">
              <label for="exampleInputEmail1">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
              <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Let's Talk.....</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
              </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        <h4>For more follow us on</h4><br><br>
        <a href="#" class="fa fa-facebook"></a>&nbsp;&nbsp;&nbsp;
        <a href="#" class="fa fa-twitter"></a>&nbsp;&nbsp;&nbsp;
        <a href="#" class="fa fa-google"></a>&nbsp;&nbsp;&nbsp;
        <a href="#" class="fa fa-instagram"></a>&nbsp;&nbsp;&nbsp;
        </div></div>
        <div class="alert alert-primary" role="alert">
             
        </div>
    </body>

</html>

templates/myapp/profile.html
{% extends "home.html" %}
{% block title %}
    <title>Profile Page</title>
{% endblock %}
{% block content %}
      <div class="container">
        <div class="jumbotron">
            <h1>Welcome to {{name}}'s Profile page</h1>
        </div>
      </div>
{% endblock %}

templates/myapp/signin.html
{% extends "home.html" %}

{% block title %}
  <title>SignIn</title>
{% endblock %}

{% block content %}
<div class="container">
    <div class="jumbotron">
<form>
    <div class="form-group">
      <label for="exampleInputEmail1">Email address</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form><br><br>
  </div></div>>
{% endblock %}

templates/myapp/signup.html
{% extends "home.html" %}

{% block title %}
  <title>SignUp</title>
{% endblock %}

{% block content %}
<div class="container">
    <div class="jumbotron">
<div> 
    <h4>Enter Name</h4>
    <div style="text-align:center">
    <input type="text" name="fname" placeholder="First name" required></div>
   
    <h4>Contact number</h4>
    <div style="text-align:center">
    <input type="number" name="phone" placeholder="Mobile" required></div>
    <h4>Date of Birth</h4>
    <div style="text-align:center">
    <input type="digit" name="dob" placeholder="D.O.B" required></div>
      
    <h4>E-mail</h4></div>
    <div style="text-align:center">
    <input type="mail" name="mail" placeholder="gmail" required></div>
  
    <h4>Address</h4>
    <div style="text-align:center">
    <input type="city" name="city" placeholder="Location/City" required></div> <br><br>

    <div style="text-align:center"> <button class="btn btn-primary"><b>Submit</b></button> <br><br>
    
</div>
</div></div>
{% endblock %}

templates/partials/_footer.html
<!-- footer -->
<div class="alert alert-primary" role="alert">
  <a href="#" class="fa fa-facebook"></a>&nbsp;&nbsp;&nbsp;
  <a href="#" class="fa fa-twitter"></a>&nbsp;&nbsp;&nbsp;
  <a href="#" class="fa fa-google"></a>&nbsp;&nbsp;&nbsp;
  <a href="#" class="fa fa-instagram"></a>&nbsp;&nbsp;&nbsp; 
  </div>

templates/partials/_navbar.html
<!--navbar-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'myapp:profile' %}">profile</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'myapp:contactus' %}">contactus</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'myapp:signin' %}">signin</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'myapp:signup' %}">signup</a>
        </li>
    
        
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>